### ISSUE TITLE
Please make possible for inclusion in Debian

### ISSUE THREAD

**Issue by irl** [hufman/flask_rdf#3]
Hi,

I'd like to include this module in Debian and use it in a Debian service. Please add an open source license to the project, preferably BSD (2 or 3 clause) or GNU GPL v2+ or v3+.

Please also tag a release in the repository or upload a release to PyPI.

Thanks,
Iain.

**Comment by hufman** [comment]
The BSD license has been included, and I've pushed a tag indicating which commit is in PyPI.

**Comment by irl** [comment]
Thanks. You can see when I've done the packaging on this bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803111

**Comment by hufman** [comment]
Glad to help! I'm more surprised anyone found this project and thinks its useful :)
