### ISSUE TITLE
nquads serialisation is attempted on graphs that do not support it

### ISSUE THREAD

**Issue by irl** [hufman/flask_rdf#4]
NQuads serialisation should only be attempted on graphs that are backed with a context-aware store, otherwise you end up with:

    Exception: NQuads serialization only makes sense for context-aware stores!

**Comment by hufman** [comment]
So if the client requests n-quad as one of the Accepts types, but the graph does not have a context, it should not consider n-quad as a valid option? That sounds easy enough.

**Comment by hufman** [comment]
Version 0.1.8 has been released which fixes this. :)
