### ISSUE TITLE
Should include Vary: Accept in HTTP response after content negotiation

### ISSUE THREAD

**Issue by osma** [hufman/flask_rdf#6]
When using the `returns_rdf` decorator, the server decides on the format and mimetype of the response based on the `Accept` HTTP header. If there's a HTTP proxy cache somewhere (e.g. Varnish or nginx as a reverse proxy) it needs to be aware that the content of the response was decided based on the Accept header value, and a different Accept header might give a different response for the same URL. The way to indicate this is simply to include the `Vary: Accept` header in the response, but flask_rdf doesn't seem to do that.

**Comment by hufman** [comment]
That is correct, I'll see if I can add this quick :)
